#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-tzdata
Version  : 2021.5
Release  : 1
URL      : https://files.pythonhosted.org/packages/9e/04/320468ac0a37db42c313dfcc24160fec94f72f23740147c5018084ea3a8a/tzdata-2021.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/9e/04/320468ac0a37db42c313dfcc24160fec94f72f23740147c5018084ea3a8a/tzdata-2021.5.tar.gz
Summary  : Provider of IANA time zone data
Group    : Development/Tools
License  : Apache-2.0
Requires: python-tzdata-license = %{version}-%{release}
Requires: python-tzdata-python = %{version}-%{release}
Requires: python-tzdata-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : wheel

%description
tzdata: Python package providing IANA time zone data
====================================================

%package license
Summary: license components for the python-tzdata package.
Group: Default

%description license
license components for the python-tzdata package.


%package python
Summary: python components for the python-tzdata package.
Group: Default
Requires: python-tzdata-python3 = %{version}-%{release}

%description python
python components for the python-tzdata package.


%package python3
Summary: python3 components for the python-tzdata package.
Group: Default
Requires: python3-core
Provides: pypi(tzdata)

%description python3
python3 components for the python-tzdata package.


%prep
%setup -q -n tzdata-2021.5
cd %{_builddir}/tzdata-2021.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1636565874
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-tzdata
cp %{_builddir}/tzdata-2021.5/LICENSE %{buildroot}/usr/share/package-licenses/python-tzdata/a17821d024ce62859b8750020c3b7cbb2e6a57af
cp %{_builddir}/tzdata-2021.5/licenses/LICENSE_APACHE %{buildroot}/usr/share/package-licenses/python-tzdata/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
python3 -m install --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-tzdata/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/python-tzdata/a17821d024ce62859b8750020c3b7cbb2e6a57af

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
